name: Release

on:
  workflow_dispatch: # Allow manual triggering
  push:
    tags:
      - 'v*' # Trigger only on tags starting with 'v'

env:
  MAVEN_URL: "https://repo1.maven.org/maven2/com/nvidia/rapids-4-spark-tools_2.12"
  PYPI_URL: "https://pypi.org/project/spark-rapids-user-tools"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:  
          token: ${{ secrets.NVAUTO_TOKEN }}

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/workflows/configuration.json" # Configuration file for the changelog builder (optional)z
          outputFile: "CHANGELOG_BODY.md"
        env:
          GITHUB_TOKEN: ${{ secrets.NVAUTO_TOKEN }}

      - name: Commit and Push Changelog
        if: steps.build_changelog.outputs.changes > 0
        run: |
          CURRENT_DATE=$(date +'%Y-%m-%d')
          BRANCH_URL=https://github.com/$GITHUB_REPOSITORY/tree/${{ github.ref_name }}
          echo -e "\n<br/>\n" > CURRENT_CHANGELOG.md
          echo "## Release [${{ github.ref_name }}]($BRANCH_URL)" >> CURRENT_CHANGELOG.md
          echo "Generated on $CURRENT_DATE" >> CURRENT_CHANGELOG.md
          cat CURRENT_CHANGELOG.md CHANGELOG_BODY.md >> TEMP_CHANGELOG.md
          cat TEMP_CHANGELOG.md CHANGELOG.md > NEW_CHANGELOG.md

          git config user.name "spark-rapids automation"
          git config user.email "70000568+nvauto@users.noreply.github.com"

          git fetch origin main
          git checkout main
          mv NEW_CHANGELOG.md CHANGELOG.md
          git add CHANGELOG.md
          git commit -s -m "Update changelogs"
          git push -f https://pxLi:${{ secrets.NVAUTO_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main

      - name: Set Version Number
        id: set_version
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION#v}  # Remove 'v' prefix
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

